# Generated by Django 4.2.26 on 2025-11-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acorde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('precio', models.IntegerField()),
                ('acordes', models.ManyToManyField(blank=True, related_name='perfumes', to='web_perfumes_app.acorde')),
                ('estaciones', models.ManyToManyField(blank=True, related_name='perfumes', to='web_perfumes_app.estacion')),
                ('notas_base', models.ManyToManyField(blank=True, related_name='perfumes_base', to='web_perfumes_app.nota')),
                ('notas_corazon', models.ManyToManyField(blank=True, related_name='perfumes_corazon', to='web_perfumes_app.nota')),
                ('notas_salida', models.ManyToManyField(blank=True, related_name='perfumes_salida', to='web_perfumes_app.nota')),
            ],
        ),
    ]
