# Generated by Django 4.2.26 on 2025-11-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
