# Generated by Django 4.2.26 on 2025-11-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0002_alter_perfume_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
    ]
