# Generated by Django 4.2.26 on 2025-11-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0003_perfume_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('U', 'Unisex')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='perfume',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='tienda',
            field=models.CharField(choices=[('SILK', 'Silk Perfumes'), ('YAURAS', 'Yauras Perfumes'), ('JOY', 'Joy Perfumes')], default='SILK', max_length=20),
        ),
        migrations.AddField(
            model_name='perfume',
            name='url_producto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
