# Generated by Django 4.2.26 on 2025-11-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0004_perfume_genero_perfume_marca_perfume_tienda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, unique=True)),
            ],
        ),
        # Eliminamos el campo de texto existente "marca" en Perfume
        migrations.RemoveField(
            model_name='perfume',
            name='marca',
        ),
        # Y creamos un nuevo campo ForeignKey "marca"
        migrations.AddField(
            model_name='perfume',
            name='marca',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='perfumes',
                to='web_perfumes_app.marca',
            ),
        ),
    ]
