# Generated by Django 4.2.26 on 2025-11-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0005_marca_alter_perfume_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='precio_ant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
