# Generated by Django 4.2.26 on 2025-11-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0006_perfume_precio_ant'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='fragantica_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
