# Generated by Django 4.2.26 on 2025-11-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0007_perfume_fragantica_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='fragantica_url',
            new_name='fragrantica_url',
        ),
    ]
