# Generated by Django 4.2.26 on 2025-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0008_rename_fragantica_url_perfume_fragrantica_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='acorde',
            name='background_rgb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
