# Generated by Django 4.2.26 on 2025-12-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0009_acorde_background_rgb'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='porcentaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
