# Generated by Django 4.2.26 on 2025-12-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0011_alter_estacion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='genero',
        ),
        migrations.AddField(
            model_name='perfume',
            name='generos',
            field=models.ManyToManyField(blank=True, null=True, related_name='perfumes', to='web_perfumes_app.genero'),
        ),
    ]
