# Generated by Django 6.0 on 2025-12-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0013_perfume_notas_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='notas_general',
            field=models.ManyToManyField(blank=True, null=True, related_name='perfumes_general', to='web_perfumes_app.nota'),
        ),
    ]
