# Generated by Django 6.0 on 2025-12-30 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0014_alter_perfume_notas_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('PERFUME', 'Perfume'), ('DECANT', 'Decant')], default='PERFUME', max_length=10)),
                ('tienda', models.CharField(choices=[('SILK', 'Silk Perfumes'), ('YAURAS', 'Yauras Perfumes'), ('JOY', 'Joy Perfumes')], max_length=20)),
                ('unidades', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.PositiveIntegerField(help_text='Precio de venta del ítem.')),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_venta', '-creado_en'],
            },
        ),
    ]
