# Generated by Django 6.0 on 2026-01-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_perfumes_app', '0015_ventaregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='es_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfume',
            name='tienda_personalizada',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='tienda',
            field=models.CharField(choices=[('SILK', 'Silk Perfumes'), ('YAURAS', 'Yauras Perfumes'), ('JOY', 'Joy Perfumes')], default='SILK', max_length=100),
        ),
    ]
