# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_perfumes_app", "0018_alter_perfume_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="marca",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="tienda",
            field=models.CharField(choices=[("SILK", "Silk Perfumes"), ("YAURAS", "Yauras Perfumes"), ("JOY", "Joy Perfumes")], default="SILK", max_length=250),
        ),
    ]
