# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_perfumes_app", "0019_alter_marca_marca_alter_perfume_tienda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acorde",
            name="background_rgb",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="ventaregistro",
            name="nombre",
            field=models.CharField(max_length=250),
        ),
    ]
