# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_perfumes_app", "0020_alter_acorde_background_rgb_alter_ventaregistro_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfume",
            name="nombre",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
