# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_perfumes_app", "0021_alter_perfume_nombre"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE web_perfumes_app_perfume ALTER COLUMN nombre TYPE varchar(250);",
            reverse_sql="ALTER TABLE web_perfumes_app_perfume ALTER COLUMN nombre TYPE varchar(100);",
        ),
        migrations.AlterField(
            model_name="perfume",
            name="nombre",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
