# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_perfumes_app", "0022_force_perfume_nombre_varchar_250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfume",
            name="nombre",
            field=models.TextField(blank=True),
        ),
    ]
