# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_perfumes_app", "0023_alter_perfume_nombre_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfume",
            name="imagen",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="perfumes/"),
        ),
    ]
